import { defineConfig } from 'tsup'

export default [
  defineConfig({
    entry: [
      'src/index.ts',
      'src/next.ts',
      'src/astro.ts',
      'src/bun.ts',
      'src/esbuild.ts',
      'src/farm.ts',
      'src/nuxt.ts',
      'src/rolldown.ts',
      'src/rollup.ts',
      'src/rspack.ts',
      'src/vite.ts',
      'src/webpack.ts',
      'src/types.ts',
    ],
    format: ['cjs', 'esm'],
    dts: false,
    splitting: false,
    sourcemap: true,
    clean: true,
    outDir: 'dist',
    external: [
      'react',
      'react-dom',
      'react/jsx-runtime',
      'next/link',
      'next/image',
      'lucide-react',
      'lucide-vue-next',
      'clsx',
      '@nuxt/kit',
      '@nuxt/schema',
      'vue',
      'svelte',
      'svelte/store',
    ],
  }),
  defineConfig({
    entry: ['src/components/index.ts', 'src/components/theme.css'],
    format: ['cjs', 'esm'],
    dts: false,
    splitting: false,
    sourcemap: true,
    clean: false,
    outDir: 'dist/components',
    external: [
      'react',
      'react-dom',
      'lucide-react',
      'clsx',
    ],
    banner: {
      js: "'use client'",
    },
  }),
]
